### ISSUE TITLE
Props when quiet mode is set.

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/nPose-V4#4]
New prop position/rotation comes from the prop itself which is a good thing.  When quiet mode is set, the prop does not report a new position, which is what should happen.

However, when PosDump is clicked in the menu or hud, the prop is reporting the original position and not the new.  I've tested V3.10 as well and PosDump also comes from the prop but it is reporting the new position/rotation.

I prefer the V3.10 action reporting the current position.  This gives us a way to get the new position/rotation when quiet mode is set.  I would change the V4 prop plugin except I do not have the non-optimized version of the prop plugin script to modify and re-optimize.  hint, hint.. lol

Unless you have a compelling objection, would you be able to provide the current non-optimized version in the prop plugin repo or send it to me please?  I've not a problem with supporting the current scripts in your absence.  V4 is so very advanced from V3.10, everyone is loving it.

**Comment by LeonaMorro** [comment]
I just uploaded the non optimized version (sorry for the delay) .
I also added a possible fix for this isssue with the commit https://github.com/nPoseTeam/nPose-Prop-Plugin/commit/4b0bc73f05eda8e6e097d469fdacfc3a19a1344b (untested)

**Comment by HowardBaxton** [comment]
Awesome, thank you.  I will be busy RL today but will do some testing as soon as I can.

**Comment by HowardBaxton** [comment]
I have tested this with perfect results.  The PosDump is working as expected now and posts up to date position and rotation of props which are set to quiet.

Closing this issue.
